[package]
name = "prohelion-wavesculptor"
authors = [
    "The Team Arrow Racing Association firmware development team",
    "Liam Kinne <liam@kinne.io>"
]
description = "Driver for the Prohelion WaveSculptor Motor Driver."
categories = ["embedded", "no-std"]
documentation = "https://docs.rs/prohelion-wavesculptor"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[lib]
name = "prohelion_wavesculptor"

[dependencies]
bitflags = "1.3.2"
num-complex = "0.4.3"
socketcan = "1.7.0"
